### PR TITLE
improve performance

### PR DESCRIPTION
**Pull request by andryua**
"choco list" and "choco list -lo" compared and added in variable "packages" field - ":latest"

### CODE REVIEW

**Comment by michaeltlombardi** [comment]
Hey, @andryua! Thanks so much for the PR! I'm going to close #119 as a duplicate of this one since the changes are identical.

I'm in the process of filing a ticket to represent this work - can you help me understand a bit more about the context of this improvement? There's a fair amount of changes in here! 😄

**Comment by lionce** [comment]
Hello @andryua ,

Thank you for your effort to improve this module. How is it going? As you can see, unit tests are failing. Also it looks like this PR needs a rebase. Do you need any help with that?

**Comment by sheenaajay** [comment]
HI @andryua . Could you please resolve the conflict. Thank you.

**Comment by david22swan** [comment]
@andryua Apologies, just checking if you are still active on this pr?

**Comment by david22swan** [comment]
@andryua 
Apologies but due to the length on time this PR has been left to lie fallow and your lack of response when pinged o it we feel that it should now be closed.
We offer are apologies if this is an inconvenience to you and look forward to any future contributions that you may choose to make.

**Pull request closed without merging**
